decoupling example
DevBetterCom/blogs.gatsby pull request #12
Opened 2022-09-09 03:59 UTC by sauravbhattacharya001

2022-09-11 01:36 UTC, KyleMcMaster requested changes
Some small typos but other than that it looks good! Thanks for the contribution!

2022-09-11 01:36 UTC, KyleMcMaster commented on src/data/author.yaml
> +  bio: Saurav is interested in making well-desingned software. In his free time, he researches about software design, well-being practices, spritituality and Nondualism.
typo: designed, spirituality

2022-09-11 03:19 UTC, KyleMcMaster approved these changes
Looks good to me, :shipit: 

I'll let @ardalis merge this PR so he can deploy whenever he gets a chance.

2022-09-12 20:09 UTC, merged

2022-09-12 20:09 UTC, ardalis commented
Good to go - sorry for delay